//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : HW546 - Knight Offline
//  @ File Name : KnightDecorator.java
//  @ Date : 4/7/2015
//  @ Author : Alican Kurutepe - 1902618
//
//




public abstract class KnightDecorator extends Knight {
	public Knight decoratedKnight;

  
        
        
}
