
import java.awt.Color;
import java.util.Random;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : HW546 - Knight Offline
//  @ File Name : MoveRandom.java
//  @ Date : 4/7/2015
//  @ Author : Alican Kurutepe - 1902618
//
//




public class MoveRandom extends Strategy {
    
    MoveRandom(Knight newKnigt){
        super(newKnigt);
    }
    @Override
    public double strategyCommand(){
        
        double headingDeg;
        Random randHeading = new Random();
        headingDeg = randHeading.nextInt(360);
        headingDeg = Math.toRadians(headingDeg);
      
        headingDeg = ((headingDeg*0.3) +  (this.getCurrentKnight().getCurrentHeading()*0.7));
        this.getCurrentKnight().setSpecialAttackDone(false);
        
        if (this.getCurrentKnight().getKnightColor() == Color.RED)
        {
            headingDeg = headingDeg - Math.toRadians(180);
        }
        
        if(this.getCurrentKnight() instanceof Rogue)
        {
            this.getCurrentKnight().setSpeed(100);
        }
        this.getCurrentKnight().setTarget(null);
               
        
        return headingDeg;
    }
}
