//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : HW546 - Knight Offline
//  @ File Name : PriestFactory.java
//  @ Date : 4/7/2015
//  @ Author : Alican Kurutepe - 1902618
//
//
import java.awt.Color;



public class PriestFactory extends SoldierFactory {
    
    public PriestFactory (Color teamColor, int basePosX, int basePosY) {
        this.setTeamColor(teamColor);
        this.setBasePosX(basePosX);
        this.setBasePosY(basePosY);
    }
    
    @Override
    public Knight CreateKnight()
    {
        Priest newPriest;
        newPriest = new Priest(this.getTeamColor(),this.getBasePosX(),this.getBasePosY());
        
        return newPriest;
                   
    }
}
