
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : HW546 - Knight Offline
//  @ File Name : RogueFactory.java
//  @ Date : 4/7/2015
//  @ Author : Alican Kurutepe - 1902618
//
//




public class RogueFactory extends SoldierFactory {
    
    public RogueFactory (Color teamColor, int basePosX, int basePosY) {
        this.setTeamColor(teamColor);
        this.setBasePosX(basePosX);
        this.setBasePosY(basePosY);
    }
    
    @Override
    public Knight CreateKnight()
    {
        Rogue newRogue;
        
        newRogue = new Rogue(this.getTeamColor(),this.getBasePosX(),this.getBasePosY());
        return newRogue;
                   
    }
    
}
