//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : HW546 - Knight Offline
//  @ File Name : Simulation.java
//  @ Date : 4/7/2015
//  @ Author : Alican Kurutepe - 1902618
//
//
import java.awt.*;
import java.util.*;

import javax.swing.Timer;



public class Simulation{
    
    private static Team redTeam = new Team(Color.RED,300,50);
    private static Team blueTeam = new Team(Color.BLUE,750,650);
    private static Display newDisplay = new Display();
    private static int stepTime = 40;
    private static int stepNum = 25;
    private static int strategyChangeTime = 1000;

  
	//public Display display;
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                newDisplay.setVisible(true);
                
             
                
                
                
              
              
                Timer simTimer = new Timer(stepTime,new simActionListener());
                simTimer.setInitialDelay(2000);
                simTimer.start();
                Timer strategyTimer = new Timer(strategyChangeTime,new strategyChooser());
                strategyTimer.start();
               
                   
                
                
                
            }
        });
    }
    
    public static Team getRedTeam()
    {
        return redTeam;
    }
    public static Team getBlueTeam()
    {
        return  blueTeam;
    }

    public static Display getNewDisplay() {
        return newDisplay;
    }

    public static int getStepTime() {
        return stepTime;
    }

    public static int getStepNum() {
        return stepNum;
    }

    



    
    
   
   
  
 
}
